---
kind: pipeline
type: kubernetes
name: barcodebuddy

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: zebardy/linuxserver-barcodebuddy
      dockerfile: Dockerfile.aarch64
      build_args:
      - BARCODEBUDDY_RELEASE=v1.5.0.4